<?php


/**
 * Class TutsPlus_Catalog_Model_Category
 */
class TutsPlus_Catalog_Model_Category extends Mage_Catalog_Model_Category {


    /**
     * @return string
     */
    public function getChildren()
    {
        die("getChild method from local");
        return parent::getChildren(); // TODO: Change the autogenerated stub
    }
}